"""
Generate README assets:
  assets/variants_demo.gif   — animated GIF cycling through all 15 dataset variants,
                               each frame drawn from a different episode/page
  assets/pipeline.png        — before/after single panel, dark background
  assets/variants_grid.png   — grid showing all variants, one panel per cell

Run from project root: python3 src/make_assets.py
Requires: data/preprocessing/renders/ (all episodes)
          data/dataset/ (generated by synthesize_dataset.py + synthesize_overlays.py)
"""

from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw, ImageFont

RENDERS = Path("data/preprocessing/renders")
DATASET = Path("data/dataset")
ASSETS  = Path("assets")
ASSETS.mkdir(exist_ok=True)

DARK = (28, 28, 28)

# Fallback episode/page used when a variant's preferred source isn't generated yet
FALLBACK_EP   = "ep01_Potion-of-Flight"
FALLBACK_PAGE = "E01P02.png"

# ── fonts ─────────────────────────────────────────────────────────────────────
def load_font(size, bold=True):
    candidates = [
        f"/usr/share/fonts/truetype/dejavu/DejaVuSans{'-Bold' if bold else ''}.ttf",
        f"/usr/share/fonts/truetype/liberation/LiberationSans{'-Bold' if bold else '-Regular'}.ttf",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            pass
    return ImageFont.load_default()

FONT_LG = load_font(20)
FONT_SM = load_font(15, bold=False)

# ── helpers ───────────────────────────────────────────────────────────────────
def fit_width(img: Image.Image, w: int) -> Image.Image:
    h = int(img.height * w / img.width)
    return img.resize((w, h), Image.LANCZOS)


def checker_bg(size, sq=12, c1=(200, 200, 200), c2=(240, 240, 240)):
    bg = Image.new("RGBA", size, c1 + (255,))
    draw = ImageDraw.Draw(bg)
    for y in range(0, size[1], sq):
        for x in range(0, size[0], sq):
            if (x // sq + y // sq) % 2 == 0:
                draw.rectangle([x, y, x + sq - 1, y + sq - 1], fill=c2 + (255,))
    return bg


def composite_on_bg(img: Image.Image, bg_color=None) -> Image.Image:
    bg = checker_bg(img.size) if bg_color is None else Image.new("RGBA", img.size, bg_color + (255,))
    bg.alpha_composite(img)
    return bg


def detect_panel_bounds(cleaned_path: Path):
    """Y bounds of the largest content panel via alpha channel."""
    img   = Image.open(cleaned_path).convert("RGBA")
    alpha = np.array(img.getchannel("A"))
    w     = alpha.shape[1]
    center = alpha[:, w // 10: 9 * w // 10]
    has_content = center.max(axis=1) > 0
    panels, in_panel, start = [], False, 0
    for i, v in enumerate(has_content):
        if v and not in_panel:
            start = i; in_panel = True
        elif not v and in_panel:
            panels.append((start, i)); in_panel = False
    if in_panel:
        panels.append((start, len(has_content)))
    if not panels:
        return 0, img.height
    return max(panels, key=lambda p: p[1] - p[0])


def crop_to_panel(img: Image.Image, y1: int, y2: int, gap: int = 18) -> Image.Image:
    r1 = max(0, y1 - gap)
    r2 = min(img.height, y2 + gap)
    return img.crop((0, r1, img.width, r2))


def label_bar(width, top_text, sub_text="", bg=DARK):
    lh = 44 if sub_text else 34
    bar = Image.new("RGBA", (width, lh), bg + (255,))
    draw = ImageDraw.Draw(bar)
    draw.text((10, 7),  top_text, font=FONT_LG, fill=(245, 245, 245))
    if sub_text:
        draw.text((10, 28), sub_text, font=FONT_SM, fill=(155, 155, 155))
    return bar


def stack_label(img: Image.Image, top_text, sub_text="") -> Image.Image:
    bar = label_bar(img.width, top_text, sub_text)
    out = Image.new("RGBA", (img.width, img.height + bar.height), DARK + (255,))
    out.paste(bar, (0, 0))
    out.paste(img, (0, bar.height))
    return out


def has_transparency(folder: str) -> bool:
    return "cleaned" in folder


# ── variant definitions ───────────────────────────────────────────────────────
# (folder, source, role, description, preferred_ep, preferred_page)
# source: "renders" → RENDERS/ep/folder/page
#         "dataset" → DATASET/ep/folder/page
# Preferred ep/page showcases each variant from a different episode.
# Falls back to FALLBACK_EP/PAGE if the preferred dataset file doesn't exist yet.
VARIANTS = [
    ("cleaned",              "renders", "Target", "transparent borders — clean artwork",      "ep05_Special-holiday-episode",      "E05P03.png"),
    ("initial",              "renders", "Input",  "raw KRA export, borders intact",           "ep09_The-Remedy",                   "E09P04.png"),
    ("black",                "dataset", "Input",  "black background",                         "ep13_The-Pyjama-Party",             "E13P03.png"),
    ("framed",               "dataset", "Input",  "white bg + 1px black frame",               "ep17_A-Fresh-Start",                "E17P04.png"),
    ("framed_cleaned",       "dataset", "Input",  "transparent bg + 1px frame",               "ep21_The-Magic-Contest",            "E21P03.png"),
    ("framed_jpeg",          "dataset", "Input",  "white bg + frame + JPEG q15",              "ep24_The-Unity-Tree",               "E24P04.png"),
    ("framed_jpeg_cleaned",  "dataset", "Input",  "transparent bg + frame + JPEG q15",        "ep27_Coriander-s-Invention",        "E27P03.png"),
    ("gradient_border",      "dataset", "Input",  "borders filled black→white gradient",      "ep30_Need-a-Hug",                   "E30P04.png"),
    ("gradient_border_inv",  "dataset", "Input",  "borders filled white→black gradient",      "ep34_The-Knighting-of-Shichimi",    "E34P05.png"),
    ("jpeg",                 "dataset", "Input",  "initial render + JPEG q15",                "ep38_The-Healer",                   "E38P04.png"),
    ("jpeg_cleaned",         "dataset", "Input",  "cleaned artwork + JPEG artifacts",         "ep02_Rainbow-potions",              "E02P03.png"),
    ("sfx_overlay",          "dataset", "Input",  "Korean SFX on initial render",             "ep06_The-Potion-Contest",           "E06P03.png"),
    ("sfx_overlay_cleaned",  "dataset", "Input",  "same SFX on cleaned artwork (RGBA)",       "ep06_The-Potion-Contest",           "E06P03.png"),
    ("bubble_overlay",       "dataset", "Input",  "speech bubbles on initial render",         "ep10_Summer-Special",               "E10P03.png"),
    ("bubble_overlay_cleaned","dataset","Input",  "same bubbles on cleaned artwork (RGBA)",   "ep15_The-Crystal-Ball",             "E15P04.png"),
]


def resolve_path(folder, source, pref_ep, pref_page):
    """Return path to variant image, preferring pref_ep, falling back to ep01."""
    if source == "renders":
        p = RENDERS / pref_ep / folder / pref_page
        return p if p.exists() else RENDERS / FALLBACK_EP / folder / FALLBACK_PAGE
    p = DATASET / pref_ep / folder / pref_page
    if p.exists():
        return p
    fallback = DATASET / FALLBACK_EP / folder / FALLBACK_PAGE
    return fallback if fallback.exists() else None


# ══════════════════════════════════════════════════════════════════════════════
# GIF — variants_demo: each frame from a different episode
# ══════════════════════════════════════════════════════════════════════════════
print("Building variants_demo.gif ...")

MAIN_W    = 580
ZOOM_SCALE = 5
ZOOM_SRC   = 20
ZOOM_DSP   = ZOOM_SRC * ZOOM_SCALE
INSET_PAD  = 4
LABEL_H    = 44

frames = []
for folder, source, role, desc, pref_ep, pref_page in VARIANTS:
    src = resolve_path(folder, source, pref_ep, pref_page)
    if src is None or not src.exists():
        print(f"  skip {folder}: no source found"); continue

    # detect panel bounds from the corresponding cleaned render
    if source == "renders" and folder == "cleaned":
        cleaned_ref = src
    else:
        ep_part = src.parts[-3]  # ep dir name
        cleaned_ref = RENDERS / ep_part / "cleaned" / src.name
        if not cleaned_ref.exists():
            cleaned_ref = RENDERS / FALLBACK_EP / "cleaned" / FALLBACK_PAGE

    py1, py2 = detect_panel_bounds(cleaned_ref)

    raw   = Image.open(src).convert("RGBA")
    panel = crop_to_panel(raw, py1, py2)
    vis   = composite_on_bg(panel) if has_transparency(folder) else composite_on_bg(panel, (255, 255, 255))
    vis   = fit_width(vis, MAIN_W)
    ph    = vis.height

    # Zoom into bottom-right area (border/artwork boundary)
    zx1 = MAIN_W * 82 // 100
    zx2 = zx1 + ZOOM_SRC
    zy1 = ph - ZOOM_SRC
    zy2 = ph

    zoom_crop = vis.crop((zx1, zy1, zx2, zy2))
    zoom_big  = zoom_crop.resize((ZOOM_DSP, ZOOM_DSP), Image.NEAREST)

    vis_m = vis.copy().convert("RGB")
    draw  = ImageDraw.Draw(vis_m)
    draw.rectangle([zx1 - 2, zy1 - 2, zx2 - 1, zy2 - 1], outline=(255, 60, 60), width=2)
    ix = MAIN_W - ZOOM_DSP - INSET_PAD
    iy = ph     - ZOOM_DSP - INSET_PAD - 45
    vis_m.paste(zoom_big.convert("RGB"), (ix, iy))
    draw.rectangle([ix - 2, iy - 2, ix + ZOOM_DSP, iy + ZOOM_DSP], outline=(255, 60, 60), width=2)

    ep_short = src.parts[-3].split("_", 1)[1].replace("-", " ")
    canvas = Image.new("RGB", (MAIN_W, LABEL_H + ph), DARK)
    bar = label_bar(MAIN_W, f"{folder.replace('_', ' ')}  —  {role}", f"{ep_short}  ·  {desc}")
    canvas.paste(bar.convert("RGB"), (0, 0))
    canvas.paste(vis_m, (0, LABEL_H))

    frames.append(canvas.convert("P", palette=Image.ADAPTIVE, colors=256))
    print(f"  {folder:<28} {src.parts[-3].split('_')[0]}/{src.name}")

frames[0].save(
    ASSETS / "variants_demo.gif",
    save_all=True, append_images=frames[1:],
    duration=2000, loop=0, optimize=False,
)
print(f"  -> assets/variants_demo.gif  ({len(frames)} frames, {MAIN_W}×{frames[0].height})")


# ══════════════════════════════════════════════════════════════════════════════
# PIPELINE — before / after
# ══════════════════════════════════════════════════════════════════════════════
print("Building pipeline.png ...")

PIPE_EP   = "ep09_The-Remedy"
PIPE_PAGE = "E09P04.png"

HALF_W_P  = 400
ARROW_W_P = 56

init_path    = RENDERS / PIPE_EP / "initial" / PIPE_PAGE
cleaned_path = RENDERS / PIPE_EP / "cleaned" / PIPE_PAGE
if not init_path.exists():
    init_path    = RENDERS / FALLBACK_EP / "initial" / FALLBACK_PAGE
    cleaned_path = RENDERS / FALLBACK_EP / "cleaned" / FALLBACK_PAGE

py1, py2 = detect_panel_bounds(cleaned_path)

def load_pipeline_panel(path, bg_color=None):
    raw   = Image.open(path).convert("RGBA")
    panel = crop_to_panel(raw, py1, py2)
    return fit_width(composite_on_bg(panel, bg_color), HALF_W_P)

before = load_pipeline_panel(init_path,    (255, 255, 255))
after  = load_pipeline_panel(cleaned_path, None)

before_lab = stack_label(before, "Before", "raw KRA export — borders intact")
after_lab  = stack_label(after,  "After",  "transparent borders — training target")

H = max(before_lab.height, after_lab.height)
W = HALF_W_P * 2 + ARROW_W_P

pipeline = Image.new("RGB", (W, H), DARK)
pipeline.paste(before_lab.convert("RGB"), (0, 0))
pipeline.paste(after_lab.convert("RGB"),  (HALF_W_P + ARROW_W_P, 0))

draw  = ImageDraw.Draw(pipeline)
mid_y = H // 2
ax0, ax1 = HALF_W_P + 8, HALF_W_P + ARROW_W_P - 8
draw.line([(ax0, mid_y), (ax1, mid_y)], fill=(180, 180, 180), width=3)
draw.polygon([(ax1, mid_y - 8), (ax1, mid_y + 8), (ax1 + 8, mid_y)], fill=(180, 180, 180))

pipeline.save(ASSETS / "pipeline.png")
print(f"  -> assets/pipeline.png  ({W}×{H})")


# ══════════════════════════════════════════════════════════════════════════════
# GRID — all variants, one panel per cell
# ══════════════════════════════════════════════════════════════════════════════
print("Building variants_grid.png ...")

CELL_W       = 360
COLS         = 3
PAD_G        = 6
GRID_ZOOM_SRC = 16
GRID_ZOOM_DSP = GRID_ZOOM_SRC * 5

cells = []
for folder, source, role, desc, pref_ep, pref_page in VARIANTS:
    src = resolve_path(folder, source, pref_ep, pref_page)
    if src is None or not src.exists():
        continue

    ep_part = src.parts[-3]
    cleaned_ref = (RENDERS / ep_part / "cleaned" / src.name
                   if source != "renders" or folder != "cleaned"
                   else src)
    if not cleaned_ref.exists():
        cleaned_ref = RENDERS / FALLBACK_EP / "cleaned" / FALLBACK_PAGE

    py1, py2 = detect_panel_bounds(cleaned_ref)

    raw   = Image.open(src).convert("RGBA")
    panel = crop_to_panel(raw, py1, py2)
    vis   = composite_on_bg(panel) if has_transparency(folder) else composite_on_bg(panel, (255, 255, 255))
    vis   = fit_width(vis, CELL_W)
    ph    = vis.height

    zx1 = CELL_W * 82 // 100
    zx2 = zx1 + GRID_ZOOM_SRC
    zy1 = ph - GRID_ZOOM_SRC
    zy2 = ph

    zoom_big = vis.crop((zx1, zy1, zx2, zy2)).resize((GRID_ZOOM_DSP, GRID_ZOOM_DSP), Image.NEAREST)

    vis_m = vis.copy().convert("RGB")
    draw  = ImageDraw.Draw(vis_m)
    draw.rectangle([zx1-2, zy1-2, zx2-1, zy2-1], outline=(255, 60, 60), width=2)
    ix = CELL_W - GRID_ZOOM_DSP - INSET_PAD
    iy = ph     - GRID_ZOOM_DSP - INSET_PAD - 30
    vis_m.paste(zoom_big.convert("RGB"), (ix, iy))
    draw.rectangle([ix-2, iy-2, ix+GRID_ZOOM_DSP, iy+GRID_ZOOM_DSP], outline=(255, 60, 60), width=2)

    ep_short = ep_part.split("_", 1)[1].replace("-", " ")
    cell = stack_label(Image.fromarray(np.array(vis_m)).convert("RGBA"),
                       folder.replace("_", " "), f"{role} — {ep_short}")
    cells.append(cell.convert("RGB"))

ROWS   = (len(cells) + COLS - 1) // COLS
cell_h = cells[0].height
GW = COLS * CELL_W + (COLS + 1) * PAD_G
GH = ROWS * cell_h + (ROWS + 1) * PAD_G
grid = Image.new("RGB", (GW, GH), (55, 55, 55))

for i, cell in enumerate(cells):
    row, col = divmod(i, COLS)
    x = PAD_G + col * (CELL_W + PAD_G)
    y = PAD_G + row * (cell_h + PAD_G)
    grid.paste(cell, (x, y))

grid.save(ASSETS / "variants_grid.png")
print(f"  -> assets/variants_grid.png  ({GW}×{GH}, {COLS}×{ROWS})")

print("\nDone.")
